name       : bismuth
version    : 3.1.3
release    : 4
source     :
    - https://github.com/Bismuth-Forge/bismuth/archive/refs/tags/v3.1.3.tar.gz : f748d4685a35401146fc887c9ab24e69056fb96261d17679184568e8a331b50b
homepage   : https://github.com/Bismuth-Forge/bismuth
license    : MIT
component  : desktop.kde
summary    : Tiling window script for KDE Plasma
description: |
    Addon for KDE Plasma to arrange your windows automatically and switch between them using keyboard shortcuts, like tiling window managers.
networking : yes
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcmutils-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdecoration-devel
    - kglobalaccel-devel
    - ki18n-devel
    - nodejs
setup      : |
    npm install
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
