name       : bismuth
version    : 2.3.0
release    : 1
source     :
    - https://github.com/Bismuth-Forge/bismuth/archive/refs/tags/v2.3.0.tar.gz : d89cf7eb956beac2a5373124eef64cc8dec80fc1bba181f56d7c2493589d7539
homepage   : https://github.com/Bismuth-Forge/bismuth
license    : MIT
component  : desktop.kde
summary    : Tiling window script for KDE Plasma
description: |
    Addon for KDE Plasma to arrange your windows automatically and switch between them using keyboard shortcuts, like tiling window managers.
networking : yes
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcmutils-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - nodejs
setup      : |
    npm install
build      : |
    npm run build
install    : |
    DESTDIR="$installdir" cmake --install build
