name       : bismuth
version    : 3.1.4
release    : 5
source     :
    - https://github.com/Bismuth-Forge/bismuth/archive/refs/tags/v3.1.4.tar.gz : 216d8f5a6c649e4950989b2d7e100fe23832311328b970b8e32985c1ef25b0b5
homepage   : https://github.com/Bismuth-Forge/bismuth
license    : MIT
component  : desktop.kde
summary    : Tiling window script for KDE Plasma
description: |
    Addon for KDE Plasma to arrange your windows automatically and switch between them using keyboard shortcuts, like tiling window managers.
networking : yes
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcmutils-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdecoration-devel
    - kglobalaccel-devel
    - ki18n-devel
    - nodejs
setup      : |
    npm install
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
